### ISSUE TITLE
PHP Notices "Undefined index"

### ISSUE THREAD

**Issue by trey8611** [soflyy/wp-all-import-rapid-addon#14]
I was working on releasing a new version of the RealHomes add-on (see: https://github.com/soflyy/wp-all-import-pro/issues/242), but I found some PHP notices when testing the new version. Examples:

> [27-Apr-2018 21:30:56 UTC] Backtrace from notice "Undefined index: address_geocode"In /var/www/public/precious-millipede/wp-content/plugins/realhomes-xml-csv-property-listings-import/rapid-addon.php [line 685]

> [27-Apr-2018 21:30:56 UTC] Backtrace from notice "Undefined index: coord_geocode"In /var/www/public/precious-millipede/wp-content/plugins/realhomes-xml-csv-property-listings-import/rapid-addon.php [line 684]

Is this an issue with the add-on itself, or is it an issue in the rapid add-on api?

Replicated here: http://precious-millipede.w6.wpsandbox.pro/?upass=Z8FqPH1vj66e.

**Comment by joeguilmette** [comment]
@trey8611 do we need to update the rapid-addon in all of our plugins?

**Comment by trey8611** [comment]
@joeguilmette I haven't tested with all of the other add-ons yet, but my guess is that we do need to update it for all add-ons. I don't think this is too critical of a problem so I didn't plan on pushing updates just for this (I don't think we've gotten any tickets about it yet either), but let me know if you think I should.

**Comment by joeguilmette** [comment]
That's fine, do whatever you think is best.
