### ISSUE TITLE
Sort post types

### ISSUE THREAD

**Issue by trey8611** [soflyy/wp-all-import-rapid-addon#16]

**Comment by joeguilmette** [comment]
Plan A: Figure out a way to have the pulldown use the same sort order we have in the menu.

Plan B: Create an endpoint to specify sort order.

Please poke around and determine if A is possible/how long it'll take.

**Comment by trey8611** [comment]
Hey @mbissett can you please have a look at this when you get a chance? According to what I'm seeing, it looks like I need to completely replace the post loop in wp-all-import-pro/views/admin/import/index.php to allow us to sort the posts. 

I've replaced the loop, and I added a function in rapid-addon.php that lets us manipulate the "menu_position" for each post via an add-on, e.g.:

```php
$my_addon->post_order_priority( array( 'post' => '100' ) );
```

But, I can't figure out how to sort the $all_posts variable based on the menu_position in the index.php loop. Any ideas on how to do this or if it's possible? Or, am I approaching this incorrectly? Any ideas/advice/help would be greatly appreciated.

**Comment by mbissett** [comment]
Hey @trey8611,

Right now, I'm seeing that WPAI sorts the list of post types by using the "wp_all_import_cmp_custom_types" function in /wp-all-import-pro/helpers/functions.php:

<pre>    if ( ! function_exists('wp_all_import_cmp_custom_types')){
        function wp_all_import_cmp_custom_types($a, $b)
        {
            return strcmp($a->labels->name, $b->labels->name);
        }
    }</pre>

In looking into this, though, I'm only seeing that "posts" & "pages" have assigned menu orders. We'll probably need to assign a menu_order value to each of the default post types, so we can still keep the usual order.

**Comment by trey8611** [comment]
@joeguilmette I had to go with plan B, but here's the function I've added by updating rapid-addon.php and 2 files in WPAI PRO core plugin:

## move_post_type

```php
$my_addon->move_post_type( $move_this [array/string - the posts to move], $move_to [array/string - position to move the post(s) to] );
```

* move_post_type - Move one or more post types in the drop down list on step 1 of an import.

### Parameters

#### $move_this

* Array or string of the post(s) to move.

#### $move_to

* Array or string of the new position(s) for the post(s).

### Examples

##### Move WooCommerce Products post type to the top of the list.

```php
$my_addon->move_post_type( 'product', 0 );
```

##### Move 3 different post types to the top 3 positions in the list.

```php
$my_addon->move_post_type( array( 'post', 'page', 'product' ), array( 0, 1, 2 ) );
```


##### Move 3 different posts to the end of the list

```php
$my_addon->move_post_type( array( 'post', 'page', 'product' ), array( 99, 99, 99 ) );
```

**Comment by trey8611** [comment]
This required a re-write of the loop that we used to lists posts, so if you like the way this function works then I'll do one more code audit and ask Max if there are any possible issues that could be caused by altering the loop in the way that I did.

**Comment by joeguilmette** [comment]
Looks great! Go for it.

**Comment by trey8611** [comment]
Hey @cmdmcs , I've had to change the post loop in /views/admin/import/index.php and /views/admin/import/options/_settings_template.php for the new functions that I'm writing in the Rapid Add-On API. Could you please review the changes and make sure that they won't break anything? You can find them in the "changes_for_rapid_addon_step_1" branch on my forked copy of WPAI:

- Lines 251 - 310 in index.php: https://github.com/trey8611/wp-all-import-pro/blob/changes_for_rapid_addon_step_1/views/admin/import/index.php#L251
- Lines 122 - 173 in _settings_template.php: https://github.com/trey8611/wp-all-import-pro/blob/changes_for_rapid_addon_step_1/views/admin/import/options/_settings_template.php#L122

**Note**: I'm still trying to think of a better way to handle the "listing_type" check for the MyListing add-on. It doesn't seem like a good idea to add that much code to these core files just for one add-on.

**Comment by joeguilmette** [comment]
> Note: I'm still trying to think of a better way to handle the "listing_type" check for the MyListing add-on. It doesn't seem like a good idea to add that much code to these core files just for one add-on.

Maybe you can add it to the add-on API? It doesn't really matter so much as long as it works and is self contained and commented.

**Comment by trey8611** [comment]
@joeguilmette I decided to add a hook for it. This, https://github.com/soflyy/wp-all-import-rapid-addon/issues/17, and https://github.com/soflyy/wp-all-import-rapid-addon/issues/15 are done and ready for testing as soon as @cmdmcs gets a chance to approve the post loop change.

**Comment by cmdmcs** [comment]
@trey8611 I reviewed your changes, looks good to me. Tested here http://lovely-grebe.w5.wpsandbox.pro/?upass=36rPsuYzZ6M2 with branch `changes_for_rapid_addon_step_1`
