### ISSUE TITLE
Resize all icons in Step 1 post type pulldown

### ISSUE THREAD

**Issue by joeguilmette** [soflyy/wp-all-import-rapid-addon#18]
Right now the default icons, added image icons, and added dashicons all render a little bit different, with different spacing. All icons should be the same size and be vertically centered along their post type label.

Width: 24px
Height: 29px

All images and icons should be proportionally scaled down to that size. The text has a height of 21px, so the icon should extend 4px above the text and 4px below the text so that it is vertically centered. 

Images and icons with a height less than 29px should be vertically centered.

<img width="518" alt="post type icons" src="https://user-images.githubusercontent.com/6581316/45151277-10ffb780-b1f8-11e8-917f-b33a97b77738.png">

**Comment by trey8611** [comment]
@joeguilmette I pushed a fix for custom images to your debug site: http://aquamarine-rook.w5.wpsandbox.pro?upass=5Js6uoGPR8w6 (make sure to use ctrl+shift+r in chrome to clear the cache and see the changes). It looks better to me, but I'm not how to measure everything exactly to be sure. Do you just use inspector for this or do you have another tool?

As for the custom dashicons, I believe they're displaying the same as all of our other dashicons always have - so, do I need to make an adjustment to *all* of the icons or are you only seeing a difference in the ones that can be added via the rapid add-on API?

**Comment by joeguilmette** [comment]
Looks great - good work. Last thing:

For the icon image, change `background-position: left center;` to `background-position: center center;`

> Do you just use inspector for this or do you have another tool?

Mostly I just use inspector, it gives you the dimensions of DOM elements.

**Comment by trey8611** [comment]
> For the icon image, change background-position: left center; to background-position: center center;

This is fixed and uploaded to your debug site.
