### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by combs** [soflyy/wp-all-import-rapid-addon#19]
Hello! I'm troubleshooting some issues with a plugin that uses rapid-addon.php and noticed that the version number in rapid-addon.php doesn't seem to get updated. 

It seems to have had some substantial differences but has kept the same 1.1.0 version number since August 2017. 

I know this is just a housekeeping thing but it would have saved me some confusion! :sweat_smile: 

Thanks,
Chris

**Comment by joeguilmette** [comment]
Thanks for the heads up! We have another update coming and will be sure to bump the version.
