### ISSUE TITLE
Using "on" as a key for the radio button options causes it to always be selected by default.

### ISSUE THREAD

**Issue by m-thomson** [soflyy/wp-all-import-rapid-addon#3]
```
$radio = array( 
 'on' => 'Enabled',
 'off' => 'Disabled',
);

$wpai_rapid->add_field('field_slug', 
  'Label text', 
  'radio', 
  $radio, 
  'help text'),
```

With this code, when creating a new import the radio option "Enabled" will always be selected on page load, even if we don't want anything preselected. Changing the 'on' key solves the problem:

```
$radio = array( 
 '_on_' => 'Enabled',
 'off' => 'Disabled',
);

$wpai_rapid->add_field('field_slug', 
  'Label text', 
  'radio', 
  $radio, 
  'help text'),

```

**Comment by joeguilmette** [comment]
IIRC the API will always select the first option by default. With a radio field it doesn't really make sense to be able to not selection one of the options. If a user selects one and then decides they want to unselect both that's not possible, right?

**Comment by joeguilmette** [comment]
To bring our discussion on Basecamp over here, it seems that something fishy is going on when using 'on' as a key in a radio field. We have yet to completely isolate the issue.
