### ISSUE TITLE
Enum/Radio values with special characters cause JS errors

### ISSUE THREAD

**Issue by tripflex** [soflyy/wp-all-import-rapid-addon#30]
This is actually related to how the API handles the output of radio/enum fields, but there is code in `wp-content/plugins/wp-all-import-pro/classes/api.php` that outputs the enum fields, specifically setting this:

```html
<input type="radio" id="<?php echo sanitize_title($params['field_name']); ?>_<?php echo $key; ?>" class="switcher" name="<?php echo $params['field_name']; ?>" value="<?php echo $key; ?>" <?php echo $key == $params['field_value'] ? 'checked="checked"': '' ?>/>
```

What ends up happening, is if the $key is something like `5'10" - 5'12"` there's numerous javascript errors 

```
Uncaught Error: Syntax error, unrecognized expression: .switcher-target-wpjm_fe_addon_jobs_job_radio_test_5'1" - 5'10"
```
This is also the case is the value is say, `> 5 feet` or `5/10ths`, etc etc

Due to `/wp-content/plugins/wp-all-import-pro/static/js/admin.js` that has this code:

```javascript
    // swither show/hide logic
	$('input.switcher').live('change', function (e) {	

		if ($(this).is(':radio:checked')) {
			$(this).parents('form').find('input.switcher:radio[name="' + $(this).attr('name') + '"]').not(this).change();
		}
		var $targets = $('.switcher-target-' + $(this).attr('id'));

		var is_show = $(this).is(':checked'); if ($(this).is('.switcher-reversed')) is_show = ! is_show;
		if (is_show) {
			$targets.slideDown();
		} else {
			$targets.slideUp().find('.clear-on-switch').add($targets.filter('.clear-on-switch')).val('');
		}
	}).change();
```

Specifically due to the selector being used:
```javascript
var $targets = $('.switcher-target-' + $(this).attr('id'));
```

Which should be changed to something like this, to escape the selector used before passing it to jQuery:
```javascript
function escapeSelector( myClass ) {
	return '.' + myClass.replace( /(\>|\<|\'|\"|:|\.|\[|\]|,|=|@|\\|\/)/g, "\\$1" );
}

var $targets = $( escapeSelector( 'switcher-target-' +  $( this ).attr( 'id' ) ) );
```

The `escapeSelector` class I pulled from jQuery's website, adding `'` `"` `<` `>` `\` `/`:
https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/

I also posted this in the WordPress Support Forums:
https://wordpress.org/support/topic/enum-radio-values-with-special-characters-cause-js-errors/

**Comment by trey8611** [comment]
Thanks for the report @tripflex - this has been fixed in WP All Import Pro v4.5.7-beta-2.2.
