### ISSUE TITLE
Add support for checkboxes fields

### ISSUE THREAD

**Issue by Chouby** [soflyy/wp-all-import-rapid-addon#7]
Hi,

Maybe I missed it, but it looks like there is no option to add a checkbox in the form using `RapidAddon::add_field()`. Is it something you plan to add? That would be useful. Of course I could use a radio button instead but it's not as elegant for a 2-states option.

**Comment by joeguilmette** [comment]
Sorry for the late reply. No, we don't have support for a checkbox and probably won't add support for one. You can use a radio option instead.
