### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by Chouby** [soflyy/wp-all-import-rapid-addon#9]
Hi,

By nature, the rapid addon, being a library, is meant to be included in 3rd party products. However no license is specified, neither in the PHP file, nor in the readme file. The license is important as it could condition the license of the derivative addon or possibly make an addon impossible to release (in case the addon would have to rely on code with an incompatible license).

After some search, I found a version used in one of your addon, [released as GPLv2 or later](https://plugins.trac.wordpress.org/browser/yoast-seo-settings-xml-csv-import/trunk/readme.txt), but it would be much better if the license was clearly stated in the library source.

**Comment by joeguilmette** [comment]
Thanks @Chouby!

@cmdmcs can you add the same license that WordPress uses to the wp-all-import-rapid-addon repo?

Thank you!

**Comment by cmdmcs** [comment]
License added. Thanks @Chouby

**Comment by Chouby** [comment]
Thank you!

@cmdmcs Just one note however. If your intention is to apply the same license as WordPress, then I suggest that you specify GPLv2 or any later version [as done by WordPress](https://github.com/WordPress/WordPress/blob/4.8.1/license.txt#L5-L8). 

The reason why the mention "or any later version" is important is because the GPL v3 is, by default, [incompatible with the GPL v2](https://www.gnu.org/licenses/license-list.en.html#GPLv2). 

So if your intention is to allow derivative works to use the GPL v2 or GPL v3 or the 2 licences, then you should add the mention. If you want to tick to the GPL v2 only, then you can keep things as is.
